# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            atomthem.es
tagline1:         'Showcasing'
tagline2:         'themes from the Atom community'
description:      'atomthem.es is a showcase of some of the great themes the Atom community has put together.'
>>>>>>> Added link to contribution guidelines in sidebar
url:              http://atomthem.es

author:
  name:           'Rhys Powell & Tony Guntharp'
  url:            http://atomthem.es/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/atom-themes/atom-themes.github.io
